### ISSUE TITLE
[feature] add support dotnet/shell command

### ISSUE THREAD

**Issue by gitlsl** [open-job/openjob#108]
[feature] 
1.add support dotnet/shell command
2.可以在页面上查看历史job运行日志

**Comment by stelin** [comment]
@gitlsl 

Job instance log is supported !

![image](https://github.com/open-job/openjob/assets/1677543/04f9ffe3-d8f0-42b5-84de-726923c7d4be)

**Comment by stelin** [comment]
@gitlsl dotnet will be supported by openapi, shell will release at 1.0.3

**Comment by stelin** [comment]
@gitlsl update to 1.0.4, support shell

**Comment by stelin** [comment]
@gitlsl dotnet 暂时没有支持计划，团队没有 dotnet 技术栈

**Comment by stelin** [comment]
如果你有这个需求，可以和我们一起开发  dotnet
