### ISSUE TITLE
新建的命名空间无法在应用管理列表页查出

### ISSUE THREAD

**Issue by BarryBarryBarry** [open-job/openjob#113]
应用管理列表页默认只会查询命名空间namespaceId=1的数据，新建的命名空间无处可查询。
<img width="967" alt="openjob-applist" src="https://github.com/open-job/openjob/assets/111278555/8d43e448-cab0-4b71-8e96-3dd74c35c6ec">

**Comment by stelin** [comment]
@BarryBarryBarry switch namespace

![image](https://github.com/open-job/openjob/assets/1677543/03de6ea9-798a-424e-90d2-83a090be8cbc)
