### ISSUE TITLE
首次登录就报错了

### ISSUE THREAD

**Issue by geekyouth** [open-job/openjob#116]
**System (please complete the following information):**

 - OS: `linux` [e.g. linux, macOS, windows]
 - JAVA Version: `1.13` [e.g. `1.13`]
 - Pkg Version: `1.1.1` [e.g. `1.1.1`]

**Describe the bug**

**To Reproduce**

```java
// java code
```

**Expected behavior**

**Screenshots**
![image](https://github.com/open-job/openjob/assets/12899262/c790133c-883d-4075-866f-9ffaaa303f39)

**Additional context**

**Comment by geekyouth** [comment]
![image](https://github.com/open-job/openjob/assets/12899262/74f98991-7a1c-4ba1-830c-112a8c3a5c2a)
这几个菜单不太正常吧？

**Comment by stelin** [comment]
这个几个菜单功能还没实现 @geekyouth

**Comment by stelin** [comment]
@geekyouth 是一个前端问题，下个版本修复

**Comment by stelin** [comment]
@geekyouth update to 1.0.4
