### ISSUE TITLE
日志集成报错

### ISSUE THREAD

**Issue by sunnyyuu** [open-job/openjob#129]
客户端是SpringBoot+Logback，当logger.info()打印一个比较长的文本日志时会报错如下，同时服务端任务日志中为空，未接收到日志内容。
[ERROR] [07/05/2023 18:35:01.024] [openjob-worker-akka.remote.default-remote-dispatcher-8] [Encoder(akka://openjob-worker)] Failed to serialize oversized message [ActorSelectionMessage(io.openjob.common.request.WorkerJobInstanceTaskLogRequest)].
akka.remote.OversizedPayloadException: Discarding oversized payload sent to Some(Actor[akka://openjob-server@192.168.0.238:25520/]): max allowed size 262144 bytes. Message type [ActorSelectionMessage(io.openjob.common.request.WorkerJobInstanceTaskLogRequest)].

**Comment by stelin** [comment]
@sunnyyuu 日志不超过长度，是否正常收集显示日志

**Comment by stelin** [comment]
超过长度，下个迭代优化下

**Comment by sunnyyuu** [comment]
> @sunnyyuu 日志不超过长度，是否正常收集显示日志

正常。

**Comment by stelin** [comment]
@sunnyyuu 下个版本优化下长度问题

**Comment by stelin** [comment]
@sunnyyuu 已修复 1.0.6
