### ISSUE TITLE
执行器是docker容器化部署，worker host应该怎么填

### ISSUE THREAD

**Issue by KakaBlce** [open-job/openjob#149]
**System (please complete the following information):**

 - OS: `linux` [e.g. linux, macOS, windows]
 - JAVA Version: `1.13` [e.g. `1.13`]
 - Pkg Version: `1.1.1` [e.g. `1.1.1`]

**Describe the bug**

**To Reproduce**

```java
// java code
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by stelin** [comment]
worker host 可以不用配置，自动获取当前机器IP
