### ISSUE TITLE
openjob管理后台注册节点显示错误，不是实际注册的应用

### ISSUE THREAD

**Issue by 18600454482** [open-job/openjob#94]
**System (please complete the following information):**

 - OS: `linux` [e.g. linux, macOS, windows]
 - JAVA Version: `1.13` [e.g. `1.13`]
 - Pkg Version: `1.1.1` [e.g. `1.1.1`]

**Describe the bug**
复现场景：
本地A服务的workder节点注册后，后台注册节点显示的A服务（正常），然后关掉A服务，B服务使用A服务的节点地址，后台注册节点仍然显示的是A服务，这样后续在执行任务的时候，会找不到服务的任务。
解决方式：
1. 本地同时使用多服务注册节点，可以绑定不同端口
2. openjob 发现节点地址相同，去更新应用名称
**To Reproduce**

```java
// java code
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by stelin** [comment]
Fixed at 1.0.2
